# Test the SeleniumBase Python package with Azure Pipelines.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-22.04'
  strategy:
    matrix:
      Browser Chrome:
        browser: 'chrome'
      # Browser Edge:
      #   browser: 'edge'
    maxParallel: 5

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      architecture: 'x64'
      
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'browserstack-connection'
      
  # - task: BrowserStackResults@1
  #   inputs:
  #     browserstackProduct: 'automate'

  - script: python -m pip install --upgrade pip && pip --version
    displayName: 'Install/upgrade pip'

  - script: python -m pip install seleniumbase
    displayName: 'Install SeleniumBase'

  - script: |
      pip install allure-pytest
    displayName: 'Install Allure Report'

  - script: python -m pytest --browser=$(browser) --alluredir=allure_results --ad-block --demo --demo-sleep=0 --highlights=20 --browser=remote --server=trungqun_NxHvTD:rGMre9ctExHXnkxxNHLT@hub.browserstack.com --port=80
    displayName: 'Run pytest using browser: $(browser)'

  - task: BrowserStackResults@1
    inputs:
      browserstackProduct: 'automate'

  - task: PublishAllureReport@1
    displayName: 'Publish Allure Report: $(browser)'
    inputs:
      reportName: 'Allure Report: $(browser)'
      allureVersion: 2.29.0
      testResultsDir: allure_results
    condition: succeededOrFailed()