# Test the SeleniumBase Python package with Azure Pipelines.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-22.04'
  strategy:
    # matrix:
    #   Browser Chrome:
    #     browser: 'chrome'
    #   Browser Edge:
    #     browser: 'edge'
    maxParallel: 5

  steps:
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'browserstack-connection'
      
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip --version
    displayName: 'Install/upgrade pip'

  - script: pip install seleniumbase
    displayName: 'Install SeleniumBase'

  - script: pip install allure-pytest
    displayName: 'Install Allure Report'

  - script: pytest tests/test_profile.py --browser=remote --server=trungqun_NxHvTD:rGMre9ctExHXnkxxNHLT@hub.browserstack.com --port=80 --cap_file=capabilities.yml --alluredir=allure_results --ad-block --demo --demo-sleep=0
    displayName: 'Run pytest'
  
  - task: BrowserStackResults@1
    inputs:
      browserstackProduct: 'automate'

  - task: PublishAllureReport@1
    displayName: 'Publish Allure Report'
    inputs:
      reportName: 'Allure Report'
      allureVersion: 2.29.0
      testResultsDir: allure_results
    condition: succeededOrFailed()