# Test the SeleniumBase Python package with Azure Pipelines.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-22.04'
  strategy:
    matrix:
      Capability Windows 11 - Chrome:
        platform: 'windows'
        browser: 'chrome'
      Capability Windows 10 - Edge:
        platform: 'win10'
        browser: 'edge'
      Capability Mac - Safari:
        platform: 'mac'
        browser: 'safari'
    maxParallel: 5

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip --version
    displayName: 'Install/upgrade pip'

  - script: pip install seleniumbase
    displayName: 'Install SeleniumBase'

  - script: pip install allure-pytest
    displayName: 'Install Allure Report'

  - script: pytest --browser=remote --server=trungqun_NxHvTD:rGMre9ctExHXnkxxNHLT@hub.browserstack.com --port=80 --cap_file=capabilities/$(platform)_$(browser).yml --alluredir=allure_results --ad-block --demo --demo-sleep=0
    displayName: 'Run test on platform: $(platform) and browser: $(browser)'

  - task: BrowserStackResults@1
    displayName: 'Automate BrowserStack result'
    inputs:
      browserstackProduct: 'automate'

  - task: PublishAllureReport@1
    displayName: 'Publish Allure Report: $(platform) $(browser)'
    inputs:
      reportName: 'Allure Report: $(browser)'
      allureVersion: 2.29.0
      testResultsDir: allure_results
    condition: succeededOrFailed()