class StudentRegistrationFormPageLocators:
    FIRST_NAME_INPUT = '#firstName'
    LAST_NAME_INPUT = '#lastName'
    EMAIL_INPUT = '#userEmail'
    MALE_RADIO_BUTTON = '//*[text()="Male"]'
    FEMALE_RADIO_BUTTON = '//*[text()="Female"]'
    OTHER_RADIO_BUTTON = '//*[text()="Other"]'
    MOBILE_NUMBER_INPUT = '#userNumber'
    DATE_OF_BIRTH_INPUT = '#dateOfBirthInput'
    DATE_PICKER_MONTH_SELECT = '.react-datepicker__month-select'
    DATE_PICKER_MONTH_OPTION = ('//*[@class="react-datepicker"]//select[@class="react-datepicker__month-select"]'
                                '//option[text()={0}]')
    DATE_PICKER_YEAR_SELECT = '.react-datepicker__year-select'
    DATE_PICKER_YEAR_OPTION = ('//*[@class="react-datepicker"]//select[@class="react-datepicker__year-select"]'
                               '//option[text()={0}]')
    DATE_PICKER_DAY_OPTION = '//*[@class="react-datepicker"]//*[@class="react-datepicker__week"]/div[@aria-label="{0}"]'
    SUBJECTS_INPUT = '#subjectsInput'
    HOBBIES_SPORTS_CHECKBOX = '//*[text()="Sports"]'
    HOBBIES_READING_CHECKBOX = '//*[text()="Reading"]'
    HOBBIES_MUSIC_CHECKBOX = '//*[text()="Music"]'
    FILE_UPLOAD_BUTTON = '#uploadPicture'
    CURRENT_ADDRESS_INPUT = '//*[@placeholder="Current Address"]'
    STATE_SELECT = '#state'
    STATE_OPTION = '//*[@id="state"]//*[text()="{0}"]'
    CITY_SELECT = '#city'
    CITY_OPTION = '//*[@id="city"]//*[text()="{0}"]'
    SUBMIT_BUTTON = '#submit'
    THANK_YOU_FOR_SUBMITTING_DIALOG = '//*[@role="dialog"]//*[text()="Thanks for submitting the form"]'
    RESULT_CELLS = '//tbody/tr/td'
    CLOSE_BUTTON = '//button[text()="Close"]'
